### ISSUE TITLE
release 版本好像挂了。

### ISSUE THREAD

**Issue by Opdoop** [youqingxiaozhua/Ucas_course_ppt_auto_download#2]
![image](https://user-images.githubusercontent.com/21202514/67135939-25631000-f252-11e9-9321-9850bebc1d90.png)
如图。好像这周挂的吧。

**Comment by Opdoop** [comment]
看 Debug 会跳转到这里
<!DOCTYPE html> <html> <head> <meta http-equiv='Content-Type' content='text/html;charset=UTF-8' /> <title>Web应用防火墙</title> </head> <style> p{line-height:20px;} ul{list-style-type:none;} li{list-style-type:none;} </style> <body style='padding:0;margin:0;font:14px/1.5 Microsoft Yahei, 宋体,sans-serif;'> <div style='margin:0 auto;width:500px;padding-top:150px;'> <div style='height:40px;line-height:40px;color:#fff;font-size:16px;padding-left:20px;background:#6bb3f6;font-weight:bold;'>请求异常 </div><div style='font-size:14px;color:#0c0f03;height:200px;line-height:24px;padding:20px 20px 0 20px;background:#f3f7f9;border:1px dashed #cdcece;border-top:0px;'><p style='margin:0px;'><span style='font-weight:600;color:#fc4f03;'>您的请求存在异常，网站管理员设置了拦截访问！</span></p><p style='margin:0px;'>拦截原因：您提交的内容符合管理员设置的攻击过滤条件</p><p>如何避免拦截：</p><ul> <li>1）请检查提交的内容</li> <li>2）网站托管访客，请联系空间提供商</li> <li>3）普通网站访客，请联系网站管理员</li> </ul> </div> </div>  </body> </html>

**Comment by Lyases** [comment]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='course.ucas.ac.cn', port=80): Max retries exceeded with url: /portal/plogin?Identity=c747f325-9235-47b5-bc77-9663b183796e&roleId=801 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x039CB230>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-------------------------------
运行脚本出现这样的错误信息是怎么回事呀

**Comment by Opdoop** [comment]
Web应用防火墙 是 SEP 的问题，等两天就好了。
